# Directory structure:
# /usr/share/dotnet/: Dotnet install directory.
# /usr/share/Hippo-Backend: Hippo-Exchange Backend Export Directory. Removed before each run.
# /usr/share/nginx/: Nginx config directory. Certain files will be removed from it.
# /usr/share/swagger-validator: The swagger-validator badge directory. Will be removed before each run.
# /srv/: HTML Files served by the webserver. Emptied before each run.
- name: Clear Old Install.
  hosts: testing
  become: true
  tasks:
    - name: Stop webserver
      block:
        - name: Stop Nginx if running.
          ansible.builtin.systemd_service:
            name: nginx
            state: stopped
            enabled: false
      rescue:
        - name: "Print warning."
          ansible.builtin.debug: 
            msg: 'NOTE{{":"}} Nginx did not stop.'
    - name: Stop validator badge
      block:
        - name: Stop Swagger Validator if running
          ansible.builtin.systemd_service:
            name: SwaggerValidatorBadge
            state: stopped
            enabled: false
      rescue:
        - name: "Print warning."
          ansible.builtin.debug: 
            msg: 'NOTE{{":"}} Swagger-Validator did not stop.'
    - name: Stop Hippo Backend
      block:
        - name: Stop Backend if running.
          ansible.builtin.systemd_service:
            name: HippoExBackend
            state: stopped
            enabled: false
      rescue:
        - name: "Print warning."
          ansible.builtin.debug: 
            msg: "NOTE: Swagger-Validator did not stop."
    - name: "Remove webpage files from /srv/."
      block:
        - name: "Remove html subdirectory."
          ansible.builtin.file:
            state: absent
            path: "/srv/html"
        - name: "Remove dev subdirectory"
          ansible.builtin.file:
            state: absent
            path: "/srv/dev"
      rescue:
        - name: "Print warning"
          ansible.builtin.debug:
            msg: "WARNING: Failed to remove folder(s) from /srv/."
    - name: "Remove API files from /usr/local/share."
      block:
        - name: "Remove HippoAPI."
          ansible.builtin.file:
            state: absent
            path: "{{dests.HippoAPI|quote}}"
        - name: "Remove Swagger-Validator."           
          ansible.builtin.file:
            state: absent
            path: "{{dests.swagger_validator|quote}}"
      rescue:
        - name: "Print warning"
          ansible.builtin.debug:
            msg: "WARNING: Failed to remove folder(s) from /usr/local/share."
    - name: "Delete and recreate sites-available directory."
      block:
        - name: "Remove sites-available"
          ansible.builtin.file:
            state: absent
            path: "{{ dests.nginx + '/sites-available/'|quote }}"
        - name: "Re-create sites-available"
          ansible.builtin.file:
            state: directory
            path: "{{ dests.nginx + '/sites-available/'|quote }}"
      rescue:
        - name: "Print warning"
          ansible.builtin.debug:
            msg: "WARNING: Failed to remove/create sites-available from {{dests.nginx}}."
    - name: "Delete and recreate sites-enabled directory."
      block:
        - name: "Remove sites-enabled"
          ansible.builtin.file:
            state: absent
            path: "{{ dests.nginx + '/sites-enabled/'|quote }}"
        - name: "Re-create sites-enabled"
          ansible.builtin.file:
            state: directory
            path: "{{ dests.nginx + '/sites-enabled/'|quote }}"
      rescue:
        - name: "Print warning"
          ansible.builtin.debug:
            msg: "WARNING: Failed to remove/create sites-enabled from {{dests.nginx}}."
    - name: "Remove Main NGINX Configuration File."
      ansible.builtin.file:
        state: absent
        path: "{{ dests.nginx + '/nginx.conf'|quote  }}"
    - name: "Clear Nginx Cache"
      block:
      - name: "Remove ansible cache directory"
        ansible.builtin.file:
          state: absent
          path: "/var/cache/nginx"
      - name: "Re-create ansible cache directory"
        ansible.builtin.file:
          state: directory
          path: "/var/cache/nginx"





