- name: Get dotnet install script
  ansible.builtin.get_url:
    url: "{{ dotnet_url }}"
    dest: "~/dotnet_install.sh"
  register: dotnet_script
- name: Set dotnet install script permissions
  ansible.builtin.file:
    path: '{{ dotnet_script.dest }}'
    mode: "a+x"
  register: dotnet_script
- name: Run dotnet install script
  ansible.builtin.command:
    cmd: '{{ dotnet_script.path }}'
    creates: '~/.dotnet/'
  register: dotnet_proc
- name: Move install to the correct location.
  ansible.builtin.command:
    argv: 
      - 'mv'
      - '~/.dotnet/'
      - '/usr/share/dotnet'
    creates: '/usr/share/dotnet/'
    removes: "~/.dotnet/" 
  become: true
  register: dotnet_install
