- name: Start services on backend.
  hosts: testing
  tasks:
    - name: Start and enable Nginx
      ansible.builtin.systemd_service:
        name: nginx
        state: started
        enabled: true
      become: true
    - name: Start and enable the Hippo Backend
      ansible.builtin.systemd_service:
        name: HippoExBackend
        state: started
        enabled: true
      become: true
    - name: Start and enable the Swagger Validator Badge Service
      ansible.builtin.systemd_service:
        name: SwaggerValidatorBadge
        state: started
        enabled: true
      become: true
