# This is a group of tasks, not a playbook.
- name: "Print unit user."
  ansible.builtin.debug:
    msg: "User: {{user|default('undefined')}}"
- name: "Print unit group."
  ansible.builtin.debug:
    msg: "Group: {{group|default('undefined')}}"
- name: "Setup Unit User Account"
  when: user is defined
  ansible.builtin.include_tasks:
    file: "user.yaml"

- name: "Create systemd unit for {{ title }} in the user scope"
  when: user_unit is true
  become: true
  ansible.builtin.template:
    src: files/service.jinja
    dest: "/etc/systemd/user/{{ title }}.service"

- name: "Create systemd unit for {{ title }} in the user scope"
  become: true
  when: user_unit is false
  ansible.builtin.template:
    src: files/service.jinja
    dest: "/etc/systemd/system/{{ title }}.service"
