- hosts: locals
  roles:
    - common

- name: Check Status of Dependencies
  async_status:
    jid: "{{ async_result_item.ansible_job_id }}"
  loop: "{{ async_results.results }}"
  loop_control:
    loop_var: "async_result_item"
  register: dependency_results
  until: dependency_results.is.finished
  retries: 30
