# Stage 1
- name: Locate local git directory
  ansible.builtin.command:
    chdir: "{{ playbook_dir }}"
    argv: 
      - git
      - rev-parse
      - --show-toplevel
  register: local_repo_out
  #delegate_to: locals
  #connection: local
- name: Register Local Git Directory
  ansible.builtin.set_fact:
    local_repo: "{{ local_repo_out.stdout }}"
- name: Pull Swagger Submodules
  ansible.builtin.command:
    chdir: "{{ local_repo }}"
    argv:
      - git
      - submodule
      - update
      - --init
      - --remote
      - --recursive
  register: submodule_proc
  async: 120
  poll: 0
- name: Store Submodule Task
  ansible.builtin.set_fact:
    local_procs: "{{local_procs | ansible.builtin.combine(dict([['submodule_proc', submodule_proc]]))}}"
  #delegate_to: locals
  #connection: local
- debug: msg="{{local_procs}}"
#- name: Register Swagger Submodule Pull Process
  #ansible.builtin.set_fact:
    #processes: "{{ processes + [dict([['name','Update local submodules'] + ['proc', submodule_proc]]) }}"
