openapi: 3.1.1
info:
  title: Hippo Exchange API
  description: The api used to manage accounts and items on the hippo exchange.
  version: 0.0.1

servers:
  # Relative to whatever host the swagger instance is running on.
  - url: /api/
    description: Requests will be sent to the url of this swagger instance.

components:
  securitySchemes:
    placeholder: # A placeholder cookie auth schema until we decide on something better.
      type: apiKey
      in: cookie
      name: SESSIONID
tags:
  - name : account
    description: Account related endpoint methods. These endpoints should validate user account information and create sessions as needed.
  - name: listing
    description: Item listing related endpoint methods. These endpoints should handle the creation, alteration, and removal of item listings.
  - name: loan
    description: Borrow-Related endpoint methods. These endpoints should handle transactions related to items being borrowed and returned. 
paths:
  /register: #Endpoint
    $ref: "endpoints/account/register.yaml#/register"
  /login:
    $ref: "endpoints/account/session.yaml#/login"
  /logout:
    $ref: "endpoints/account/session.yaml#/logout"
  /me:
    $ref: "endpoints/account/session.yaml#/me"
  # The item listing endpoints.
  /items:  
    $ref: "endpoints/listing/items.yaml#/~1items"
  /items/{id}:
    $ref: "endpoints/listing/items.yaml#/~1items~1{id}"
  
