openapi: 3.1.1
info:
  title: Hippo Exchange API
  description: The api used to manage accounts and items on the hippo exchange.
  version: 0.0.1

servers:
  # Relative to whatever host the swagger instance is running on.
  - url: /api/
    description: Requests will be sent to the url of this swagger instance.

paths:
  /register:
    post:
      summary: Creates a new user account.
      description: Validates the user's information, then uses it to add a new account to the database if it is valid and the account doesn't already exist.
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fname:
                  type: string
                  description: The user's first name.
                lname:
                  type: string
                  description: The user's last name.
                bday:
                  type: string
                  format: date
                  description: The user's date of birth (YYYY-MM-DD).
                email:  
                  type: string
                  description: The user's email address.
                phone:
                  type: string
                  description: The user's phone number.
                password:
                  type: string
                  description: The user's password.
                confirm_password:
                  type: string
                  description: The user's password again.
                terms:
                  type: string
                  description: \"on\" if the terms box was checked, \"off\" otherwise.
      responses:
        "200":
          description: A message indicating success is returned.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: There was an issue with the provided user input.
          content:
            application/json:
              schema:
                type: object
                properties:
                  fname:
                    type: string
                  lname:
                    type: string
                  bday:
                    type: string
                  email:  
                    type: string
                  phone:
                    type: string
                  password:
                    type: string
                  confirm_password:
                    type: string
                  terms:
                    type: string
