openapi: 3.1.1
info:
  title: Hippo Exchange API
  description: The api used to manage accounts and items on the hippo exchange.
  version: 0.0.1

servers:
  # Relative to whatever host the swagger instance is running on.
  - url: /api/
    description: Requests will be sent to the url of this swagger instance.

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
